- id: dart_todo_check
  name: Dart TODO Check
  entry: scripts/dart_todo_check.dart
  language: script
  types: [dart]
  stages: [pre-commit]
- id: prevent_direct_push
  name: Prevent Direct Push to Master/Develop
  entry: scripts/prevent_direct_push.dart
  language: script
  stages: [pre-push]
