- id: dart_todo_check
  name: Dart TODO Check
  entry: dart scripts/dart_todo_check.dart
  language: system
  types: [dart]
  stages: [pre-commit]
- id: prevent_direct_push
  name: Prevent Direct Push to Master/Develop
  entry: dart scripts/prevent_direct_push.dart
  language: system
  stages: [pre-push, pre-commit]
